name: messenger
port: 30007
deployment:
  replicas: 3
  env:
    NOTIFY_QUEUE: "NOTIFY_QUEUE"
    CREATE_AUTHOR_QUEUE: "CREATE_AUTHOR_QUEUE"

authService: auth-service
public:
  - path: "/ping"
    method: "GET"
    id: "GET_PING"

  - path: "/health"
    method: "GET"
    id: "GET_HEALTH"
